[project]
name = "finalproject-petekhov-m25-555"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "Artem Petekhov", email = "apetekhov@gmail.com" }]
dependencies = [
    "prettytable >=3.16.0,<4.0.0"
]

[project.scripts]
project = "valutatrade_hub.main:main"

# Группы зависимостей (Poetry-специфика — оставляем в [tool.poetry.*])
[tool.poetry.group.dev.dependencies]
ruff = "^0.14.2"

# Указываем, какие пакеты включать в wheel
[tool.poetry]
packages = [{ include = "valutatrade_hub" }]

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = ["venv", ".venv", "dist", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"